// Post slug -> image path mapping (date-based folders)
// Path format: images/YYYY/<topic-key>.png
const POST_IMAGES = {
  // ===== 2019 =====
  'react-from-scratch-v1': '2019/react-vintage.png',
  'libgdx-hello-world': '2019/libgdx-intro.png',
  'jme3-basics': '2019/jme3-intro.png',
  'react-v1-migration': '2019/react-vintage.png',
  'libgdx-scene2d': '2019/libgdx-intro.png',
  'nodejs-event-loop-deep-dive': '2019/nodejs-deep.png',
  'react-setstate-patterns': '2019/react-hooks-era.png',
  'jme3-terrain-generation': '2019/jme3-3d.png',
  'microservices-with-nodejs': '2019/microservices.png',
  'react-context-api': '2019/react-hooks-era.png',
  'fractal-intro': '2019/fractal-math.png',
  'hex-grid-basics': '2019/hex-grid.png',
  'react-hooks-intro': '2019/react-hooks-era.png',
  'libgdx-box2d-physics': '2019/libgdx-intro.png',
  'nodejs-streams': '2019/nodejs-deep.png',
  'fractal-ifs': '2019/fractal-math.png',
  'react-native-intro': '2019/react-native.png',
  'spatial-indexing-quadtree': '2019/hex-grid.png',
  'rest-vs-graphql-node': '2019/microservices.png',
  'react-v16-fiber': '2019/react-fiber.png',
  'jme3-model-loading': '2019/jme3-3d.png',
  'fractal-lsystems': '2019/fractal-math.png',
  'hex-pathfinding': '2019/hex-grid.png',
  'nodejs-cluster': '2019/nodejs-deep.png',
  'react-v16-lifecycles': '2019/react-fiber.png',
  'libgdx-particle-effects': '2019/libgdx-intro.png',
  'event-driven-architecture': '2019/microservices.png',
  'react-error-boundaries': '2019/react-vintage.png',
  'mandelbrot-deep-zoom': '2019/fractal-math.png',
  'solidjs-first-look': '2019/react-fiber.png',
  'hex-map-rendering': '2019/hex-grid.png',
  'nestjs-first-app': '2019/microservices.png',
  'jme3-shaders': '2019/jme3-3d.png',
  'react-reconciliation': '2019/react-fiber.png',
  'fractal-flame': '2019/fractal-math.png',
  'spatial-indexing-grid': '2019/hex-grid.png',
  'nestjs-microservices': '2019/microservices.png',
  'react-v17-no-new-features': '2019/react-vintage.png',
  'libgdx-ecs-architecture': '2019/libgdx-intro.png',
  'angular-ivy': '2019/react-native.png',
  'hex-distance-math': '2019/hex-grid.png',
  'fractal-buddhabrot': '2019/fractal-math.png',
  'nestjs-graphql': '2019/microservices.png',
  'jme3-gui-nifty': '2019/jme3-3d.png',
  'react-server-components-intro': '2019/react-hooks-era.png',
  'solidjs-signals-vs-hooks': '2019/react-hooks-era.png',
  'logistic-optimization-intro': '2019/logistics.png',
  'libgdx-tiled-maps': '2019/libgdx-intro.png',
  'nestjs-websockets': '2019/microservices.png',
  'fractal-visual-programming': '2019/fractal-math.png',
  'spatial-indexing-rstar': '2019/hex-grid.png',
  'react-v18-concurrent': '2019/react-hooks-era.png',
  'grasshopper-optimization': '2019/logistics.png',
  'jme3-water-effects': '2019/jme3-3d.png',

  // ===== 2020 =====
  'fractal-doom-fire': '2020/fractal-fire.png',
  'causal-graphs-intro': '2020/causal-graph.png',
  'react-native-vs-solid': '2020/frontend-compare.png',
  'nestjs-cqrs': '2020/nestjs-advanced.png',
  'fractal-menger-sponge': '2020/fractal-fire.png',
  'graph-db-comparison': '2020/graph-db.png',
  'hex-field-of-view': '2020/hex-fov.png',
  'solidjs-mounting': '2020/frontend-compare.png',
  'react-suspense': '2020/react-suspense.png',
  'hypergraph-concept': '2020/hypergraph.png',
  'nestjs-testing': '2020/nestjs-advanced.png',
  'di-basics': '2020/nestjs-advanced.png',
  'fractal-3d-mandelbrot': '2020/fractal-fire.png',
  'causal-discovery': '2020/causal-graph.png',
  'spatial-indexing-grid-vs-tree': '2020/hex-fov.png',
  'react-portals': '2020/react-suspense.png',
  'angular-signals-preview': '2020/frontend-compare.png',
  'hypergraph-vs-property-graph': '2020/hypergraph.png',
  'nodejs-backpressure': '2020/nodejs-stream.png',
  'libgdx-ashley-ecs': '2020/libgdx-ecs.png',
  'react-v18-transitions': '2020/react-suspense.png',
  'fractal-noise-terrain': '2020/fractal-fire.png',
  'graph-neural-networks': '2020/graph-db.png',
  'nestjs-rabbitmq': '2020/nestjs-advanced.png',
  'hex-generation-algorithms': '2020/hex-fov.png',
  'react-memo-patterns': '2020/react-suspense.png',
  'autoregressive-models': '2020/autoregressive.png',
  'fractal-art-tools': '2020/fractal-fire.png',
  'angular-v13': '2020/frontend-compare.png',

  // ===== 2021 =====
  'llm-intro': '2021/llm-attention.png',
  'causal-inference-ml': '2021/causal-ml.png',
  'react-18-strict-mode': '2021/react-18.png',
  'diffusion-models-intro': '2021/diffusion.png',
  'hypergraph-storage-engine': '2021/hypergraph-engine.png',
  'nestjs-kafka': '2021/nestjs-kafka.png',
  'fractal-architecture': '2021/fractal-patterns.png',
  'react-query-vs-swr': '2021/react-18.png',
  'logistic-vrp': '2021/logistics-vrp.png',
  'solidjs-v1': '2021/solidjs-signals.png',
  'gpt-fine-tuning': '2021/llm-attention.png',
  'hypergraph-query-language': '2021/hypergraph-engine.png',
  'jme3-physics-bullet': '2021/jme3-physics.png',
  'angular-standalone': '2021/angular-evolution.png',
  'react-native-reanimated': '2021/react-native-anim.png',
  'logistic-grasshopper-deep': '2021/logistics-vrp.png',
  'spatial-octree': '2021/octree-3d.png',
  'transformer-attention': '2021/llm-attention.png',
  'react-18-automatic-batching': '2021/react-18.png',
  'hypergraph-vs-rdf': '2021/hypergraph-engine.png',
  'nestjs-grpc': '2021/nestjs-kafka.png',
  'fractal-complexity': '2021/fractal-patterns.png',
  'react-native-skia': '2021/react-native-anim.png',
  'logistic-warehouse': '2021/logistics-vrp.png',
  'react-server-components': '2021/react-18.png',
  'hypergraph-visualization': '2021/hypergraph-engine.png',
  'solidjs-v2-roadmap': '2021/solidjs-signals.png',

  // ===== 2022 =====
  'chatgpt-prompt-engineering': '2022/prompt-engineering.png',
  'dit-diffusion-transformers': '2022/dit-model.png',
  'react-19-actions': '2022/react-19.png',
  'hypergraph-query-performance': '2022/hypergraph-exec.png',
  'causal-graph-learning': '2022/causal-ml.png',
  'nestjs-event-sourcing': '2022/nestjs-kafka.png',
  'fractal-compression': '2022/fractal-patterns.png',
  'react-native-hermes': '2022/react-native-anim.png',
  'llm-agents': '2022/llm-agents.png',
  'uploopjs-concept': '2022/uploop-vision.png',
  'logistic-metaheuristics': '2022/logistics-vrp.png',
  'react-19-use': '2022/react-19.png',
  'angular-v16-signals': '2022/angular-signals.png',
  'fractal-visual-programming-tools': '2022/fractal-patterns.png',
  'hypergraph-execution-engine': '2022/hypergraph-exec.png',
  'nestjs-cache': '2022/nestjs-kafka.png',
  'react-19-compiler': '2022/react-19.png',
  'llm-rag-patterns': '2022/llm-agents.png',
  'spatial-bvh': '2022/octree-3d.png',
  'solidjs-v2-signals': '2022/solidjs-signals.png',
  'dit-training': '2022/dit-model.png',
  'hypergraph-vs-neo4j': '2022/hypergraph-exec.png',
  'react-native-vision-camera': '2022/react-native-anim.png',
  'logistic-simulation': '2022/logistics-vrp.png',

  // ===== 2023 =====
  'i2c-ecosystem-intro': '2023/i2c-ecosystem.png',
  'anigo-ai-animation': '2023/anigo.png',
  'long-polyglot-runtime': '2023/long-runtime.png',
  'jigsaw-trust-verification': '2023/jigsaw.png',
  'long-ir-design': '2023/long-runtime.png',
  'anigo-motion-synthesis': '2023/anigo.png',
  'lac-runtime-layer': '2023/lac.png',
  'uploop-vided-ai-video': '2023/uploop-vided.png',
  'long-boa-parity': '2023/long-runtime.png',
  'jigsaw-cbor-evidence': '2023/jigsaw.png',
  'uploopjs-entity-system': '2023/uploop-entity.png',
  'anigo-sgm-framework': '2023/anigo.png',
  'long-hypergraph-visibility': '2023/long-runtime.png',
  'lac-engine-swap': '2023/lac.png',
  'uploop-stream-binary': '2023/uploop-stream.png',
  'jigsaw-7-crates': '2023/jigsaw.png',
  'anigo-timeline-system': '2023/anigo.png',
  'long-v03-dataflow': '2023/long-runtime.png',
  'uploop-ge-gpu-engine': '2023/uploop-ge.png',
  'lac-capability-model': '2023/lac.png',

  // ===== 2024 =====
  'long-polyglot-design': '2024/long-polyglot.png',
  'uploop-bridges-react': '2024/uploop-bridges.png',
  'anigo-ai-agent-director': '2024/anigo-director.png',
  'hypergraph-fluid-substrate': '2024/fluid-substrate.png',
  'long-standard-modules': '2024/long-modules.png',
  'uploop-vided-mcp-server': '2024/uploop-vided-mcp.png',
  'jigsaw-trust-grading': '2024/jigsaw-grading.png',

  // ===== 2025 =====
  'fluidy-compiler-runtime': '2025/fluidy.png',
  'long-vs-deno-bun': '2025/long-bench.png',
  'ring-dht-hypergraph': '2025/rings-dht.png',
  'uploop-flows-profiles': '2025/uploop-flows.png',
  'jigsaw-content-addressing': '2025/jigsaw-content.png',
  'long-native-capability': '2025/long-native.png',
  'anigo-procedural-rigging': '2025/anigo-rigging.png',
  'uploop-server-ssr': '2025/uploop-server.png',
  'hypergraph-ai-manifest': '2025/hypergraph-ai.png',
  'logistic-multi-objective': '2025/logistics-optim.png',
  'dit-vs-gan-vs-ar': '2025/dit-compare.png',
  'hypergraph-temperature-routing': '2025/hypergraph-temp.png',
  'solidjs-v2-release': '2025/solidjs-v2.png',

  // ===== 2026 =====
  'mydevblog-relaunch': '2026/blog-relaunch.png',
  'hypergraph-current-state': '2026/hypergraph-2026.png',
  'long-current-status': '2026/long-2026.png',
  'jigsaw-rust-crates': '2026/jigsaw-2026.png',
  'uploopjs-v08': '2026/uploop-2026.png',
  'anigo-2026-progress': '2026/anigo-2026.png',
  'lac-runtime-architecture': '2026/lac-2026.png',
  'uploop-vided-v02': '2026/vided-2026.png',
  'anigo-sgm-architecture': '2026/anigo-sgm-2026.png',
  'fluidy-current-state': '2026/fluidy-2026.png',
  'rings-dht-rust': '2026/rings-2026.png',
  'uploop-bridges-current': '2026/bridges-2026.png',
  'hypergraph-polygon-runtime': '2026/polygon-2026.png',
  'long-polyglot-frontends': '2026/long-frontends.png',

  // ===== Pre-2019: SGMedia =====
  'sgmedia-founding-story': '2013/sgmedia-startup.png',
  'sgmedia-financial-struggle': '2014/sgmedia-finance.png',
  'nodejs-unity-realtime': '2014/nodejs-unity.png',
  'unity-mmorpg-nodejs': '2015/unity-mmo.png',
  'youtube-game-saturation': '2015/youtube-market.png',
  'sgmedia-pivot-lessons': '2016/sgmedia-pivot.png',
  'unity-webgl-deployment': '2016/unity-webgl.png',
  'opensource-game-frameworks': '2017/atomixgame-org.png',
  'tonegodgui-jme': '2017/tonegodgui.png',
  'sgmedia-closure': '2018/sgmedia-closure.png',

  // ===== 2019 Personal =====
  'move-to-santa-monica': '2019/santa-monica.png',
  'jme-tutorials-atomixgame': '2019/jme-tutorials.png',
  'atlanta-tech-scene': '2019/atlanta-tech.png',

  // ===== 2024-2026 AI =====
  'ai-video-generation-2024': '2024/ai-video-gen.png',
  'google-flow-ux': '2024/google-flow.png',
  'fal-ai-replicate-comparison': '2024/fal-vs-replicate.png',
  'wavespeed-models': '2025/wavespeed.png',
  'gpu-renting-nightmare': '2025/gpu-renting.png',
  'self-deploy-ai-models': '2025/self-deploy-ai.png',
  'replicate-model-taste': '2025/ai-model-taste.png',
  '3d-model-ai-generation': '2025/ai-3d-models.png',
  'audio-generation-2025': '2025/ai-audio.png',
  'google-flow-image-2026': '2026/google-flow-2026.png',
  'fal-ai-2026-progress': 'icons/fal-vs-replicate.png',
  'ai-animation-workflow-2026': 'icons/ai-video-gen.png',
};
