// POSTS_EXTRA — additional posts merged into the main index
const POSTS_EXTRA = [
  // ===== 2013–2018 SGMedia era =====
  { slug:'sgmedia-founding-story', title:'SGMedia: Founding a Game Studio in the YouTube Era', date:'2013-06-15', excerpt:'How I started SGMedia in Vietnam, the financial reality of game dev, and why YouTube saturation changed everything.', topic:'SGMedia', tags:['sgmedia','startup','gamedev','youtube'], readTime:12 },
  { slug:'sgmedia-financial-struggle', title:'Bootstrapping Through the Trough: SGMedia Financial Lessons', date:'2014-03-10', excerpt:'Cash flow management, failed monetization experiments, and the hard decisions that kept the studio alive.', topic:'SGMedia', tags:['sgmedia','startup','finance','lessons'], readTime:10 },
  { slug:'nodejs-unity-realtime', title:'Building Real-Time Game Ecosystems with Node.js and Unity', date:'2014-08-22', excerpt:'Architecture for large-scale multiplayer games using Node.js signaling servers, Unity clients, and WebSocket meshes.', topic:'Game Dev', tags:['nodejs','unity','realtime','websocket','multiplayer'], readTime:14 },
  { slug:'unity-mmorpg-nodejs', title:'Scaling an MMORPG Backend with Node.js Clusters', date:'2015-02-18', excerpt:'Zone sharding, Redis pub/sub, and physics arbitration across multiple Node.js processes for a Unity MMO.', topic:'Game Dev', tags:['unity','nodejs','mmo','scaling','redis'], readTime:13 },
  { slug:'youtube-game-saturation', title:'The YouTube Game Market: Why I Quit and What I Learned', date:'2015-09-05', excerpt:'The 2015 YouTube gaming bubble, adpocalypse effects, and when to pivot instead of doubling down.', topic:'SGMedia', tags:['sgmedia','youtube','gaming','market'], readTime:9 },
  { slug:'sgmedia-pivot-lessons', title:'SGMedia Pivot: From Games to Interactive Media', date:'2016-04-12', excerpt:'The pivot from pure game development to interactive media production — and the technical challenges that came with it.', topic:'SGMedia', tags:['sgmedia','pivot','interactive','media'], readTime:8 },
  { slug:'unity-webgl-deployment', title:'Unity WebGL: Porting Desktop Games to the Browser', date:'2016-11-20', excerpt:'Technical challenges and solutions for deploying Unity games via WebGL, including memory management and asset streaming.', topic:'Game Dev', tags:['unity','webgl','browser','deployment'], readTime:8 },
  { slug:'opensource-game-frameworks', title:'Open Sourcing Game Frameworks: The atomixgame Story', date:'2017-05-10', excerpt:'Why I open-sourced tonegodgui and other JME frameworks under atomixgame, and how the community shaped them.', topic:'Game Dev', tags:['atomixgame','opensource','jme','community'], readTime:7 },
  { slug:'tonegodgui-jme', title:'tonegodgui: Building a Complete UI System for JME3', date:'2017-08-28', excerpt:'Architecture deep-dive into the tonegodgui UI framework — layout, skinning, and event handling in JME3.', topic:'Game Dev', tags:['tonegodgui','jme3','ui','framework'], readTime:10 },
  { slug:'sgmedia-closure', title:'The Last Year of SGMedia: What Survived and What Didn\'t', date:'2018-03-15', excerpt:'Closing the studio, distributing IP, and the technical artifacts that outlived the company.', topic:'SGMedia', tags:['sgmedia','closure','legacy','lessons'], readTime:9 },

  // ===== 2019 updates: Santa Monica, Atlanta, tutorials =====
  { slug:'move-to-santa-monica', title:'Relocating to Santa Monica: A Dev\'s First Taste of Silicon Beach', date:'2019-03-01', excerpt:'Moving from Vietnam to Santa Monica, CA — the culture shock, the tech scene, and coding by the pier.', topic:'Personal', tags:['santa-monica','relocation','personal'], readTime:6 },
  { slug:'jme-tutorials-atomixgame', title:'Writing JME Tutorials and Building atomixgame on GitHub', date:'2019-04-20', excerpt:'The story behind the JME3 tutorial series, the atomixgame GitHub org, and teaching 3D game dev to thousands.', topic:'Game Dev', tags:['jme3','tutorials','opensource','atomixgame'], readTime:7 },
  { slug:'atlanta-tech-scene', title:'From Santa Monica to Atlanta: Southern Tech and New Roots', date:'2019-08-15', excerpt:'Why I moved from California to Georgia, the Atlanta tech ecosystem, and how it compares to Silicon Beach.', topic:'Personal', tags:['atlanta','relocation','tech','personal'], readTime:5 },

  // ===== 2024+ AI Provider deep dives =====
  { slug:'ai-video-generation-2024', title:'AI Video Generation in 2024: Providers Compared', date:'2024-03-05', excerpt:'Hands-on with Runway, Pika, and Stable Video Diffusion — which models deliver cinematic results and which waste your budget.', topic:'AI', tags:['ai','video','generation','comparison'], readTime:11 },
  { slug:'google-flow-ux', title:'Google Flow: Why UI/UX Matters More Than Model Quality', date:'2024-05-18', excerpt:'Google Flow\'s interface sets the gold standard for AI creative tools — even when the underlying models aren\'t the best.', topic:'AI', tags:['google-flow','ui-ux','ai-tools','design'], readTime:8 },
  { slug:'fal-ai-replicate-comparison', title:'Fal.ai vs Replicate: Pricing, Latency, and Model Quality', date:'2024-07-22', excerpt:'A head-to-head technical comparison of two leading AI inference providers across image, video, and audio models.', topic:'AI', tags:['fal-ai','replicate','comparison','pricing'], readTime:10 },
  { slug:'wavespeed-models', title:'WaveSpeed: Fast Inference for Real-Time AI Applications', date:'2024-09-10', excerpt:'Testing WaveSpeed\'s real-time AI inference pipeline for video generation and what "fast" actually means in practice.', topic:'AI', tags:['wavespeed','inference','realtime','performance'], readTime:9 },
  { slug:'gpu-renting-nightmare', title:'Renting GPUs: The Hidden Costs Nobody Talks About', date:'2025-01-20', excerpt:'Personal experience with Lambda, Vast, RunPod, and TensorDock — pricing surprises, spot instance gotchas, and when to just use an API.', topic:'AI', tags:['gpu','renting','cloud','pricing','personal'], readTime:12 },
  { slug:'self-deploy-ai-models', title:'Self-Deploying AI Models: A Personal Cost-Benefit Autopsy', date:'2025-04-08', excerpt:'Training and serving FLUX, SDXL, and Whisper on rented hardware — the DevOps pain, the cost spreadsheets, and when it actually made sense.', topic:'AI', tags:['self-deploy','training','inference','cost-analysis'], readTime:14 },
  { slug:'replicate-model-taste', title:'AI Model Taste: What I Actually Like vs What Benchmarks Say', date:'2025-06-15', excerpt:'Personal aesthetic preferences across image models — why I dislike hyper-realistic SD and keep coming back to artistic LoRAs.', topic:'AI', tags:['models','taste','aesthetics','personal'], readTime:7 },
  { slug:'3d-model-ai-generation', title:'3D Model Generation with AI: Current State and Gaps', date:'2025-09-01', excerpt:'Testing Meshy, Point-E, and Zero-1-to-3 for game asset pipelines — where AI 3D shines and where it embarrassingly fails.', topic:'AI', tags:['3d','generation','ai','game-assets'], readTime:10 },
  { slug:'audio-generation-2025', title:'AI Audio Generation: Music, SFX, and Voice in 2025', date:'2025-11-10', excerpt:'Comparing ElevenLabs, MusicGen, Suno, and Stable Audio for game development sound pipelines.', topic:'AI', tags:['audio','music','sfx','generation','comparison'], readTime:9 },
  { slug:'google-flow-image-2026', title:'Google Flow Image Generation: The UI/UX King Gets Better', date:'2026-02-10', excerpt:'Google Flow\'s 2026 image generation update — how better models finally match the excellent interface experience.', topic:'AI', tags:['google-flow','image-generation','2026','ui-ux'], readTime:7 },
  { slug:'fal-ai-2026-progress', title:'Fal.ai in 2026: New Models, Lower Prices, Same API', date:'2026-04-22', excerpt:'Fal.ai\'s 2026 roadmap and how their model catalog expansion changes the build-vs-buy calculation for AI features.', topic:'AI', tags:['fal-ai','2026','pricing','models'], readTime:8 },
  { slug:'ai-animation-workflow-2026', title:'My 2026 AI Animation Workflow: From Prompt to Render', date:'2026-06-15', excerpt:'The complete pipeline I use for AI-assisted animation — combining AniGo, Replicate, WaveSpeed, and custom control nets.', topic:'AniGo', tags:['anigo','ai','animation','workflow','2026'], readTime:13 },
];
